### ISSUE TITLE
Add Benchmark Comparison to RustFFT

### ISSUE THREAD

**Issue by mert-kurttutan** [zama-ai/concrete-fft#21]
Thanks for the project!
In case it is useful for you, and don't already have in mind. Another high performance rust fft library is RustFFT.
It might be useful to see how your project does in comparison to RustFFT (also RealFFT which does a few nice optimization tricks using RustFFT in case of real vectors).
I can try such a comparison when I have the time.

**Comment by IceTDrinker** [comment]
Hello @mert-kurttutan I see rustfft in the dev dependencies of the crate so I'm guessing we are using that for benchmarking purposes ?

**Comment by mert-kurttutan** [comment]
Ohh, yeah. I just check the top part of the file. Then, it might still be worth to check realfft if you want to provide more optimized api for Real FFTs

**Comment by IceTDrinker** [comment]
what do you mean Real FFTs ? @mert-kurttutan 🙂

**Comment by mert-kurttutan** [comment]
Sorry should have been more accurate. I meant RealtoComplex FFT.
Just like original FFT, but the elements of input the vector are real (or imaginary part equal to zero).
Really useful for some audio/image processing methods where the data consists of real numbers

**Comment by IceTDrinker** [comment]
I think that's what we do :) we have real data going in the complex domain, I could be wrong though maybe @sarah-ek could tell you a bit more !

**Comment by mert-kurttutan** [comment]
I could not see anything specific regarding the reality condition. To me (from the apis and docs), the inputs are supposed to be vectors of `c64` with the length of power of 2. Nothing else.

**Comment by IceTDrinker** [comment]
ah you are right, my bad, I think it's a trick to use less data in the fourier domain related to how the frequency spectrum behaves

**Comment by mert-kurttutan** [comment]
Yes, that is exactly what I meant in my first message

**Comment by sarah-ek** [comment]
this project makes a few different design decisions compared to rustfft as our use case is primarily polynomial multiplication. this means that in the implementation we use (`concrete_fft::unordered::Plan`) we don't mind if the elements of the polynomials in the fourier domain are permuted, and we're also only interested in power of two polynomial sizes.

these constraints allow us to perform some aggressive optimizations that fftw/rustfft can't do, so a direct comparison would be unfair. i also don't know if such constraints would be practical for other applications of the fourier transform (signal processing, etc.)
