### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by On0n0k1** [zama-ai/concrete-fft#29]
Hello.

Lucas Lemos

Great work with TFHE and all its features.

I'm making a project that requires the usage of a server key in webassembly format. Having wasm support would be great due to its compatibility with the majority of popular platforms. I read the issues related to wasm and decided to implement it myself.

The first issue I found was when deserializing a server key. Runtime mentioned that "std::time::Instant is not implemented for wasm". I fixed it by using the Performance API for Javascript. A simple implementation of it can be found here: https://github.com/zama-ai/concrete-fft/compare/main...On0n0k1:concrete-fft:main

In the implementation above, I created a custom implementation of Instant that returns the duration in Microseconds. There is an issue with using Performance though. In Google Chrome, the precision is in nanoseconds. In Mozilla Firefox, the precision is just milliseconds. Using this implementation in Firefox would cause issues because of this snippet:

if duration < MIN_DURATION {
    n_runs *= 2;
} else {
    break (n_runs, duration_div_f64(duration, n_runs as f64));
}

MIN_DURATION is just 1 ms. So Firefox precision would become a problem since duration will always be either 1 or 0.

The error vanished at least. But, when deserializing a server key, it now freezes the browser. I was looking into the source code and found a few parts that may need to be implemented specifically for wasm:
 - Generators and seeders with csprng;
 - Parallel computing using Promises;
 - Implementations for js_on_wasm_api https://github.com/zama-ai/tfhe-rs/tree/main/tfhe/src/js_on_wasm_api
 
 Noticed that memory size is a big issue in Wasm. What other issues may happen when it comes to having server keys in wasm?
 
 By discussing it, we get closer to finding a solution to the topic.

**Comment by IceTDrinker** [comment]
Hello @On0n0k1 

Feel free to open relevant issues for wasm on the TFHE-rs repo, we know that the wasm build is only really usable for the client side of things given wasm is 32 bits, several parts of the code assumes a 64 bits system.

We do not have the resources to support wasm, so contributions are welcome.

As for the timer for wasm feel free to open a PR as well, we’ll review it and let you know if we think we can integrate the code change.

Cheers

**Comment by IceTDrinker** [comment]
Please check the already existing wasm issue it’s been reported before

**Comment by On0n0k1** [comment]
Thank you @IceTDrinker.

I read the other issues. Just wanted to say that I managed to fix server key deserialization and computations on webassembly. I will create a new fork, include the necessary changes as simple commits and make a pull request for you to take a look. Is that Okay?

Kind regards,
Lucas Lemos

**Comment by IceTDrinker** [comment]
> Thank you @IceTDrinker.
> 
> I read the other issues. Just wanted to say that I managed to fix server key deserialization and computations on webassembly. I will create a new fork, include the necessary changes as simple commits and make a pull request for you to take a look. Is that Okay?
> 
> Kind regards, Lucas Lemos

Sounds good if you have tests in addition it would be great, you’ll have to sign a CLA for us to be able to accept the contribution, then we’ll take the time to review things depending on which repo you contribute to

**Comment by On0n0k1** [comment]
Sure. It is a very simple addition. I was wondering about the tests though. To test in a wasm runtime, we can use wasm-bindgen tests. To run the tests for the wasm target, there is need to setup the runtime with a tool like wasm-pack: https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/usage.html

I can implement the unit test, but the github action for it will have to be included later as well. Is that ok?

**Comment by IceTDrinker** [comment]
@On0n0k1 open the PR we'll see then

**Comment by On0n0k1** [comment]
#30 

Hope you like the fix. Just signed it.

Setting up the test for wasm runtime will require a little more effort.
